services:
  frontend:
    image: nginx:latest
    container_name: miniflix-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: miniflix-backend
    ports:
      - "5000:5000"

  mysql-db:
    image: mysql:latest
    container_name: miniflix-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

