services:
  frontend:
    image: nginx:latest
    container_name: web-frontend
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ../frontend/nginx.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build: ../backend
    container_name: web-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: web-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

